"""
Custom ReportLab canvas for dynamic 'Page X of Y' pagination and running headers.
"""

from reportlab.pdfgen import canvas
from reportlab.lib import colors


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas that computes total page count and prints running headers and footers."""

    doc_title: str = "LocalStudy Lecture Guide"
    show_header: bool = False

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        # Skip header/footer on page 1 (Cover page)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#718096"))

        # Running Header: only draw if explicitly enabled (keeps project name on 1st page only)
        if getattr(self, "show_header", False) and self.doc_title:
            self.drawString(54, 750, self.doc_title)
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Running Footer
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 38, page_str)
        self.drawString(54, 38, "Generated by LocalStudy • 100% Offline Study Toolkit")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 50, 558, 50)

        self.restoreState()
